# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloPermisoRolUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_creacion', models.CharField(max_length=100)),
                ('fec_creacion', models.DateTimeField()),
                ('usr_edicion', models.CharField(max_length=100)),
                ('fec_edicion', models.DateTimeField()),
                ('modulopermisorol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.ModuloPermisoRol')),
            ],
            options={
                'db_table': 'MODULO_PERMISO_ROL_USUARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('usr_creacion', models.CharField(max_length=100)),
                ('fec_creacion', models.DateTimeField()),
                ('usr_edicion', models.CharField(max_length=100)),
                ('fec_edicion', models.DateTimeField()),
            ],
            options={
                'db_table': 'TIPO_USUARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('ape_pat', models.CharField(blank=True, max_length=50, null=True)),
                ('ape_mat', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_contrato_inicio', models.DateField()),
                ('fecha_contrato_extended', models.DateField()),
                ('fecha_contrato_fin', models.DateField()),
                ('fecha_nacimiento', models.DateField()),
                ('email_inst', models.CharField(blank=True, max_length=100, null=True)),
                ('email_personal', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=100)),
                ('usr_creacion', models.CharField(max_length=100)),
                ('fec_creacion', models.DateTimeField()),
                ('usr_edicion', models.CharField(max_length=100)),
                ('fec_edicion', models.DateTimeField()),
                ('tipousuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.TipoUsuario')),
            ],
            options={
                'db_table': 'USUARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuariosOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('navegador_detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Usuario')),
            ],
            options={
                'db_table': 'USUARIO_ONLINE',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='modulopermisorolusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Usuario'),
        ),
    ]
