# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_auto_20161219_1610'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modulopermisorolusuario',
            unique_together=set([('usuario', 'modulopermisorol')]),
        ),
    ]
