# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('slug', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=8)),
                ('usr_creacion', models.CharField(max_length=100)),
                ('fec_creacion', models.DateTimeField()),
                ('usr_edicion', models.CharField(max_length=100)),
                ('fec_edicion', models.DateTimeField()),
                ('modulo_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Modulo')),
            ],
            options={
                'db_table': 'MODULO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModuloPermiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Modulo')),
            ],
            options={
                'db_table': 'MODULO_PERMISO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModuloPermisoRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_creacion', models.CharField(max_length=100)),
                ('fec_creacion', models.DateTimeField()),
                ('usr_edicion', models.CharField(max_length=100)),
                ('fec_edicion', models.DateTimeField()),
                ('modulopermiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.ModuloPermiso')),
            ],
            options={
                'db_table': 'MODULO_PERMISO_ROL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('codigo', models.CharField(max_length=8)),
                ('dom_name_sufijo', models.CharField(max_length=100)),
                ('usr_creacion', models.CharField(max_length=100)),
                ('fec_creacion', models.DateTimeField()),
                ('usr_edicion', models.CharField(max_length=100)),
                ('fec_edicion', models.DateTimeField()),
            ],
            options={
                'db_table': 'PERMISO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('anio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cod_meta', models.CharField(max_length=8)),
                ('usr_creacion', models.CharField(max_length=100)),
                ('fec_creacion', models.DateTimeField()),
                ('usr_edicion', models.CharField(max_length=100)),
                ('fec_edicion', models.DateTimeField()),
            ],
            options={
                'db_table': 'PROYECTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProyectoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_creacion', models.CharField(max_length=100)),
                ('fec_creacion', models.DateTimeField()),
                ('usr_edicion', models.CharField(max_length=100)),
                ('fec_edicion', models.DateTimeField()),
                ('proyectos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Proyecto')),
            ],
            options={
                'db_table': 'PROYECTO_SISTEMA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('codigo', models.CharField(max_length=8)),
                ('usr_creacion', models.CharField(max_length=100)),
                ('fec_creacion', models.DateTimeField()),
                ('usr_edicion', models.CharField(max_length=100)),
                ('fec_edicion', models.DateTimeField()),
            ],
            options={
                'db_table': 'ROL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('codigo', models.CharField(max_length=8)),
                ('usr_creacion', models.CharField(max_length=100)),
                ('fec_creacion', models.DateTimeField()),
                ('usr_edicion', models.CharField(max_length=100)),
                ('fec_edicion', models.DateTimeField()),
            ],
            options={
                'db_table': 'SISTEMA',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='proyectosistema',
            name='sistemas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Sistema'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='sistemas',
            field=models.ManyToManyField(through='seguridad.ProyectoSistema', to='seguridad.Sistema'),
        ),
        migrations.AddField(
            model_name='modulopermisorol',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Rol'),
        ),
        migrations.AddField(
            model_name='modulopermiso',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Permiso'),
        ),
        migrations.AddField(
            model_name='modulopermiso',
            name='roles',
            field=models.ManyToManyField(through='seguridad.ModuloPermisoRol', to='seguridad.Rol'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='permisos',
            field=models.ManyToManyField(through='seguridad.ModuloPermiso', to='seguridad.Permiso'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='proyectosistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.ProyectoSistema'),
        ),
    ]
