# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modulopermiso',
            unique_together=set([('permiso', 'modulo')]),
        ),
        migrations.AlterUniqueTogether(
            name='modulopermisorol',
            unique_together=set([('modulopermiso', 'rol')]),
        ),
        migrations.AlterUniqueTogether(
            name='proyectosistema',
            unique_together=set([('proyectos', 'sistemas')]),
        ),
    ]
