# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_auto_20161220_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
