# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='id_siga',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='proyecto',
            unique_together=set([('id_siga',)]),
        ),
    ]
