# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0007_auto_20161220_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='sigla',
            field=models.CharField(max_length=50),
        ),
    ]
