# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0009_sistema_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='sigla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
