# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectosSiga',
            fields=[
                ('id', models.IntegerField(db_column=b'id', primary_key=True, serialize=False)),
                ('annio_meta', models.CharField(blank=True, db_column=b'annio_meta', max_length=4, null=True)),
                ('codi_meta', models.CharField(blank=True, db_column=b'codi_meta', max_length=4, null=True)),
                ('cod_proyecto', models.CharField(blank=True, db_column=b'cod_proyecto', max_length=4, null=True)),
                ('desc_proyecto', models.CharField(blank=True, db_column=b'desc_proyecto', max_length=255, null=True)),
                ('CODI_DEPE_TDE', models.CharField(blank=True, db_column=b'CODI_DEPE_TDE', max_length=4, null=True)),
                ('codi_depe_apro', models.CharField(blank=True, db_column=b'codi_depe_apro', max_length=4, null=True)),
                ('sigla', models.CharField(blank=True, db_column=b'sigla', max_length=50, null=True)),
            ],
            options={
                'db_table': 'V_PROYECTOS_SIGA',
                'managed': False,
            },
        ),
    ]
